# MySQL 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: wjavld0269!
  jpa:
    show-sql: true # true 설정시 JPA 쿼리문 확인 가능
    hibernate:
      ddl-auto: create-drop # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    properties:
      hibernate:
        format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
